name: "Plan Terraform on pull requests"

on:
  pull_request:

jobs:
  terraform:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      - name: Terraform Format Check
        run: terraform fmt -recursive -check

      - name: Terraform Init
        run: |
          cd live/stage
          terraform init
    